In [1]:
#pip install gensim: thư viện hỗ trợ cài đặt mô hình word2vec
#pip install tensorflow: thư viện học máy hỗ trợ cài đặt, huấn luyện và kiểm thử mô hình
#pip install sklearn: thư viện hỗ trợ cài đặt các thuật toán cơ bản như SVM, ANN

In [2]:
import re
import xlrd
import pyvi
import numpy as np
import pandas as pd
from pyvi import ViTokenizer

loc = ("C:/Users/DELL/(K) Khanh_graduates_excellently/2. data_cleaning/raw_dataset.xlsx")
raw_data = xlrd.open_workbook(loc)

train_sheet = raw_data.sheet_by_index(0)
test_sheet = raw_data.sheet_by_index(1)

train_list1 = []
for i in range(train_sheet.nrows):
    train_list1.append(train_sheet.cell_value(i, 0))
test_list1 = []
for i in range(test_sheet.nrows):
    test_list1.append(test_sheet.cell_value(i, 0))

train_list2 = []
for x in train_list1:
    for y in x.split("< > *"):
        train_list2.append(y)
train_list3 = []
train_part_list = []
for i in range(len(train_list2)):
    if i%2 == 0:
        train_list3.append(train_list2[i])
    if i%2 != 0:
        train_part_list.append(train_list2[i])
train_list4 = []
for x in train_list3:
    for y in x.split(" < > "):
        train_list4.append(y)
train_part_list_scores = []
for i in range(len(train_list4)):
    if i%2 != 0:
        train_part_list_scores.append(train_list4[i])
    if i%2 == 0:
        pass

test_list2 = []
for x in test_list1:
    for y in x.split("< > *"):
        test_list2.append(y)
test_list3 = []
test_part_list = []
for i in range(len(test_list2)):
    if i%2 == 0:
        test_list3.append(test_list2[i])
    if i%2 != 0:
        test_part_list.append(test_list2[i])
test_list4 = []
for x in test_list3:
    for y in x.split(" < > "):
        test_list4.append(y)
test_part_list_scores = []
for i in range(len(test_list4)):
    if i%2 != 0:
        test_part_list_scores.append(test_list4[i])
    if i%2 == 0:
        pass    

space_replacing1 = re.compile("[^a-zA-Z_0-9ÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹế\\s]")
space_replacing2 = re.compile("(<br\s*/><br\s*/>)|(\-)|(\/)|(\n)")

def space_cleaning (reviews):
    cleaned_reviews = []
    for review in reviews:
        review = space_replacing1.sub(" ", str(review).lower())
        review = space_replacing2.sub(" ", str(review))
        review = " ".join(review.split())
        cleaned_reviews.append(review)
    return cleaned_reviews

train_clean = space_cleaning(train_part_list)
test_clean = space_cleaning(test_part_list)

def review_tokenizing (reviews):
    tokenized_reviews = []
    for review in reviews:
        tokenized_reviews.append(ViTokenizer.tokenize(review))
    return tokenized_reviews

tokenized_train = review_tokenizing(train_clean)
tokenized_test = review_tokenizing(test_clean)

stop_words = []
stop_words = [line.strip('\n') for line in open('vietnamese-stopwords-dash.txt', 'r', encoding='utf-8')]

def stop_words_removing (reviews):
    final = []
    for review in reviews: 
        removed = []
        for word in review.split(" "):
            if (word not in stop_words):
                removed.append(word)
        final.append(" ".join(removed))
    return final

final_train = stop_words_removing(tokenized_train)
final_test = stop_words_removing(tokenized_test)

print(final_train)
print(len(final_train))
print(train_part_list_scores)
print(len(train_part_list_scores))
print(" ")
print(" ")
print(" ")
print(final_test)
print(len(final_test))
print(test_part_list_scores)
print(len(test_part_list_scores))

['khách_sạn đẹp phòng sạch_sẽ nhân_viên nhiệt_tình lắm ổn', 'sai mường khen _giá _các nhân_viên cực_kì thân_thiện _mình đêm sn tặng bánh kem _sảnh rộng đẹp ngon sát biển _nội thất kk sạch_sẽ _đi nhân_viên cười giúp ko _khu vui_chơi trẻ sữa chữa hơi tiếc', 'ok', 'địa_điểm thuân tiện trang thiết_bị hiện_đại', 'ks sạch_sẽ nhân_viên nhiệt_tình tiền', 'cải_thiện thái_độ phục_vụ đội_ngũ nhân_viên bãi biển', 'phòng_ốc sạch_sẽ nhân_viên lịch_sự', 'đẹp giá_cả ok', 'ks phuc vụ dv ok ko dv bãi biển nhan viên ko kh ks ko hướng_dẫn m m mường miễn_cưỡng khăn hải_sản ko tùm_lum ko hài_lòng dv ng bãi biển thoi ok tàu xí xô xí xào suốt thiệt nhức sảnh', 'trung_tâm khách_sạn phòng hướng trực_diện biển tầm thoáng đẹp khách_sạn sang_trọng yên_tĩnh đông đoàn du_lịch tour nội_thất phòng bình_thường màu thảm trải sàn cảm_giác sạch_sẽ nội_thất xấu khách_sạn 5 có_nhân_viên đi đường tắm biển novotel ô_tô xe_máy chạy cửa khách_sạn đông lao rầm_rập đường biển sợ rớt tim nhân_viên thân_thiện trừ bộ_phận lễ_tân nhâ

In [3]:
#1, Xây dựng bộ từ vựng
#2, Biểu diễn mỗi từ thành các one-hot-vector
#3, Xây dựng word2vec

In [4]:
#pip install nltk gensim wordcloud: gensim (used for topic modeling, document indexing, and similarity retrieval)
import gensim
from gensim.models import Word2Vec
import matplotlib.pyplot as plt
from bisect import bisect_left 

In [11]:
#1, Xây dựng bộ từ vựng
word_dict = []

for review in final_train:
    for word in review.split(" "):
        if word not in word_dict:
            word_dict.append(word)
for review in final_test:
    for word in review.split(" "):
        if word not in word_dict:
            word_dict.append(word)

print(word_dict)
print(len(word_dict))

['khách_sạn', 'đẹp', 'phòng', 'sạch_sẽ', 'nhân_viên', 'nhiệt_tình', 'lắm', 'ổn', 'sai', 'mường', 'khen', '_giá', '_các', 'cực_kì', 'thân_thiện', '_mình', 'đêm', 'sn', 'tặng', 'bánh', 'kem', '_sảnh', 'rộng', 'ngon', 'sát', 'biển', '_nội', 'thất', 'kk', '_đi', 'cười', 'giúp', 'ko', '_khu', 'vui_chơi', 'trẻ', 'sữa', 'chữa', 'hơi', 'tiếc', 'ok', 'địa_điểm', 'thuân', 'tiện', 'trang', 'thiết_bị', 'hiện_đại', 'ks', 'tiền', 'cải_thiện', 'thái_độ', 'phục_vụ', 'đội_ngũ', 'bãi', 'phòng_ốc', 'lịch_sự', 'giá_cả', 'phuc', 'vụ', 'dv', 'nhan', 'viên', 'kh', 'hướng_dẫn', 'm', 'miễn_cưỡng', 'khăn', 'hải_sản', 'tùm_lum', 'hài_lòng', 'ng', 'thoi', 'tàu', 'xí', 'xô', 'xào', 'suốt', 'thiệt', 'nhức', 'sảnh', 'trung_tâm', 'hướng', 'trực_diện', 'tầm', 'thoáng', 'sang_trọng', 'yên_tĩnh', 'đông', 'đoàn', 'du_lịch', 'tour', 'nội_thất', 'bình_thường', 'màu', 'thảm', 'trải', 'sàn', 'cảm_giác', 'xấu', '5', 'có_nhân_viên', 'đi', 'đường', 'tắm', 'novotel', 'ô_tô', 'xe_máy', 'chạy', 'cửa', 'lao', 'rầm_rập', 'sợ', 'rớt'

In [12]:
#2, Biểu diễn mỗi từ thành các one-hot-vector

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
#gán index cho các từ trong từ điển bằng LabelEncoder
le = LabelEncoder()
le.fit(word_dict)
print('Words dict: ', le.classes_)
print(len(le.classes_))
# Biến đổi sang dạng số, mỗi từ trong từ điển được gán 1 số
x = le.transform(word_dict)
print('Words dict inverted into numbers: ', x)
print(len(x))
# Biến đổi lại sang class
print('Words dict inverted into classes: ', le.inverse_transform(x))
print(len(le.inverse_transform(x)))

Words dict:  ['' '0' '00' ... 'ứ_đọng' 'ứng' 'ứng_xử']
6336
Words dict inverted into numbers:  [2438 6181 3862 ... 2725 3955 6062]
6336
Words dict inverted into classes:  ['khách_sạn' 'đẹp' 'phòng' ... 'lotte' 'pv' 'đáo']
6336


In [14]:
#Thực hiện OneHotEncoder cho từ điển
oh = OneHotEncoder()
classes_indices = list(zip(le.classes_, np.arange(len(le.classes_))))
print('Words dict with indices: ,\n', classes_indices)
print(len(classes_indices))
print(" ")
print(" ")
oh.fit(classes_indices)
print('Arrays of categories and indices: ,\n', oh.categories_)
print(" ")
print(" ")
# Biến đổi từ điển sang dạng one-hot
words_indices = list(zip(word_dict, x))
print('Words dict inverted into corresponding indices: ,\n', words_indices)
print(len(words_indices))
print(" ")
one_hot = oh.transform(words_indices).toarray()
print('Words dict into one-hot matrices: \n', one_hot)
print(len(one_hot))
print(" ")
print('Words dict with indices inverted from one-hot matrices: \n', oh.inverse_transform(one_hot))
print(len(oh.inverse_transform(one_hot)))

Words dict with indices: ,
 [('', 0), ('0', 1), ('00', 2), ('000', 3), ('000d', 4), ('000vnd', 5), ('000vnf', 6), ('000đ', 7), ('01', 8), ('02', 9), ('03', 10), ('04', 11), ('05', 12), ('06', 13), ('07', 14), ('08', 15), ('09', 16), ('093', 17), ('0m7', 18), ('1', 19), ('10', 20), ('100', 21), ('1000', 22), ('1002', 23), ('1004', 24), ('100k', 25), ('100m', 26), ('101', 27), ('105', 28), ('108', 29), ('10am', 30), ('10c', 31), ('10cm', 32), ('10g', 33), ('10h', 34), ('10h30', 35), ('10k', 36), ('10km', 37), ('10m2', 38), ('10p', 39), ('10ph', 40), ('10phút', 41), ('10đ', 42), ('11', 43), ('114', 44), ('11g', 45), ('11h', 46), ('11h30', 47), ('11km', 48), ('11t', 49), ('12', 50), ('120', 51), ('1205', 52), ('120k', 53), ('120m2', 54), ('120usd', 55), ('129', 56), ('12cm', 57), ('12g', 58), ('12h', 59), ('12h00', 60), ('12m2', 61), ('12ng', 62), ('13', 63), ('130', 64), ('130k', 65), ('132b', 66), ('13h', 67), ('13h30', 68), ('14', 69), ('144', 70), ('14g', 71), ('14h', 72), ('14h00', 73

Words dict into one-hot matrices: 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
6336
 
Words dict with indices inverted from one-hot matrices: 
 [['khách_sạn' 2438]
 ['đẹp' 6181]
 ['phòng' 3862]
 ...
 ['lotte' 2725]
 ['pv' 3955]
 ['đáo' 6062]]
6336


In [15]:
#3, Xây dựng word2vec trên bộ dữ liệu train

from gensim.models import Word2Vec
#word2vec bằng gensim, có thời gian sẽ làm cách chi tiết ko dùng gensim
sentences = [[item.lower() for item in doc.split()] for doc in final_train]
w2v_model = Word2Vec(sentences, min_count = 1, vector_size = 150, window = 10, sg = 1, workers = 8)
#min_count = int - Ignores all words with total absolute frequency lower than this.
#Change to using a model that always returns something for any word, like FastText – which will try to synthesize a vector for unknown words, using subwords learned during training.
#vector_size = int - Dimensionality of the feature vectors.
#window: Kích thước cửa sổ được sử dụng để khởi tạo các n-gram.
#sg: Nhận 2 giá trị {0, 1}. Nếu là 0: phương pháp CBOW, nếu là 1: skip-grams.
#wokers: Số core CPU được huy động để huấn luyện. Càng nhiều core tốc độ huấn luyện càng nhanh.
w2v_model.train(sentences, total_examples = w2v_model.corpus_count, epochs = 10)
#Một Epoch được tính là khi chúng ta đưa tất cả dữ liệu vào mạng neural network 1 lần.
#Khi dữ liệu quá lớn, chúng ta không thể đưa hết mỗi lần tất cả tập dữ liệu vào để huấn luyện được. Buộc lòng chúng ta phải chia nhỏ tập dữ liệu ra thành các batch (size nhỏ hơn),
#số thành phần (number of batch), mỗi phần có kích thước là batch size.

# Ex: Lấy véc tơ biểu diễn của từ "hồ"
print('Embedding vector shape: ', w2v_model.wv['hồ'].shape)
print(w2v_model.wv['hồ'])
print(" ")
# Ex: Lấy các từ có mối liên hệ gần nhất với 1 từ dựa trên khoảng cách
print(w2v_model.wv.most_similar(positive=['hồ']))
print(" ")
print(w2v_model.wv.similarity('hồ', 'bơi'))
print(w2v_model.wv.similarity('hồ', 'vô_cực'))
print(w2v_model.wv.similarity('hồ', 'nước_ngọt'))
print(" ")
print(w2v_model.wv.similarity('hồ', 'bếp'))

Embedding vector shape:  (150,)
[ 0.41330352  0.10737369 -0.21447143  0.0256517  -0.69456154  0.25843447
  0.04632553  0.5335      0.03260771  0.1377218   0.2263708  -0.08794129
 -0.18226415  0.33011526 -0.07382608  0.04067613  0.16540152 -0.09296975
 -0.0037239  -0.1726189  -0.2371061  -0.26373747  0.03677104  0.25749612
 -0.0960457   0.22982545 -0.21682988 -0.10764647  0.2623624  -0.22762169
 -0.29051805  0.06781421 -0.00470141 -0.32955965  0.04407272  0.28113386
  0.80800134  0.17244528 -0.04444946  0.0566983  -0.40881217  0.15865333
  0.04128421 -0.23505393  0.53348213 -0.22996956 -0.21838517  0.09316591
  0.13239874  0.03091756 -0.21921198  0.25706774 -0.10712719 -0.2744839
  0.01847097 -0.05718586 -0.15379938 -0.04348333  0.47466594 -0.07058779
 -0.1880739  -0.5203659  -0.21480983 -0.04193642  0.03074762 -0.22554323
 -0.08653503  0.14581887 -0.62037957 -0.24529396  0.25371164  0.10368709
 -0.05933194  0.02625647  0.33015162 -0.31238872  0.09940717  0.11932214
  0.2704583   0.0279

In [16]:
print(sentences)
print(w2v_model.corpus_count)

[['khách_sạn', 'đẹp', 'phòng', 'sạch_sẽ', 'nhân_viên', 'nhiệt_tình', 'lắm', 'ổn'], ['sai', 'mường', 'khen', '_giá', '_các', 'nhân_viên', 'cực_kì', 'thân_thiện', '_mình', 'đêm', 'sn', 'tặng', 'bánh', 'kem', '_sảnh', 'rộng', 'đẹp', 'ngon', 'sát', 'biển', '_nội', 'thất', 'kk', 'sạch_sẽ', '_đi', 'nhân_viên', 'cười', 'giúp', 'ko', '_khu', 'vui_chơi', 'trẻ', 'sữa', 'chữa', 'hơi', 'tiếc'], ['ok'], ['địa_điểm', 'thuân', 'tiện', 'trang', 'thiết_bị', 'hiện_đại'], ['ks', 'sạch_sẽ', 'nhân_viên', 'nhiệt_tình', 'tiền'], ['cải_thiện', 'thái_độ', 'phục_vụ', 'đội_ngũ', 'nhân_viên', 'bãi', 'biển'], ['phòng_ốc', 'sạch_sẽ', 'nhân_viên', 'lịch_sự'], ['đẹp', 'giá_cả', 'ok'], ['ks', 'phuc', 'vụ', 'dv', 'ok', 'ko', 'dv', 'bãi', 'biển', 'nhan', 'viên', 'ko', 'kh', 'ks', 'ko', 'hướng_dẫn', 'm', 'm', 'mường', 'miễn_cưỡng', 'khăn', 'hải_sản', 'ko', 'tùm_lum', 'ko', 'hài_lòng', 'dv', 'ng', 'bãi', 'biển', 'thoi', 'ok', 'tàu', 'xí', 'xô', 'xí', 'xào', 'suốt', 'thiệt', 'nhức', 'sảnh'], ['trung_tâm', 'khách_sạn', 'phò

In [17]:
#reducing dimensionality of the words to 2 dimensions using tSNE with final_train dataset
import matplotlib.pyplot as plt
from sklearn.decomposition import IncrementalPCA    # inital reduction
from sklearn.manifold import TSNE                   # final reduction

def reduce_dimensions(model):
    num_dimensions = 2  # final num dimensions (2D, 3D, etc)

    # extract the words & their vectors, as numpy arrays
    vectors = np.asarray(model.wv.vectors)
    labels = np.asarray(model.wv.index_to_key)  # fixed-width numpy strings

    # reduce using t-SNE
    tsne = TSNE(n_components=num_dimensions, random_state=0)
    vectors = tsne.fit_transform(vectors)

    x_vals = [v[0] for v in vectors]
    y_vals = [v[1] for v in vectors]
    return x_vals, y_vals, labels


x_vals, y_vals, labels = reduce_dimensions(w2v_model)

def plot_with_plotly(x_vals, y_vals, labels, plot_in_notebook=True):
    from plotly.offline import init_notebook_mode, iplot, plot
    import plotly.graph_objs as go

    trace = go.Scatter(x=x_vals, y=y_vals, mode='text', text=labels)
    data = [trace]

    if plot_in_notebook:
        init_notebook_mode(connected=True)
        iplot(data, filename='word-embedding-plot')
    else:
        plot(data, filename='word-embedding-plot.html')


def plot_with_matplotlib(x_vals, y_vals, labels):
    import matplotlib.pyplot as plt
    import random

    random.seed(0)

    plt.figure(figsize=(12, 12))
    plt.scatter(x_vals, y_vals)

    #
    # Label randomly subsampled 25 data points
    #
    indices = list(range(len(labels)))
    selected_indices = random.sample(indices, 25)
    for i in selected_indices:
        plt.annotate(labels[i], (x_vals[i], y_vals[i]))

try:
    get_ipython()
except Exception:
    plot_function = plot_with_matplotlib
else:
    plot_function = plot_with_plotly

plot_function(x_vals, y_vals, labels)